# Generated by Django 3.2.7 on 2021-10-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0002_alter_student_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['mssv']},
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
